src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $endDate = null;

    #[ORM\Column]
    private ?bool $isPrivate = null;

    #[ORM\Column]
    private ?bool $isFinancialParticipation = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $financialParticipationAmount = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $Category = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $organisator = null;

    #[ORM\OneToMany(mappedBy: 'event', targetEntity: Registration::class)]
    private Collection $registrations;

    #[ORM\Column(length: 255)]
    private ?string $place = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $totalAmountCollected = null;

    #[ORM\OneToMany(mappedBy: 'event', targetEntity: Payment::class)]
    private Collection $payments;

    #[ORM\OneToMany(mappedBy: 'event', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->registrations = new ArrayCollection();
        $this->payments = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function isIsPrivate(): ?bool
    {
        return $this->isPrivate;
    }

    public function setIsPrivate(bool $isPrivate): static
    {
        $this->isPrivate = $isPrivate;

        return $this;
    }

    public function isIsFinancialParticipation(): bool
    {
        return $this->isFinancialParticipation ?? false;
    }

    public function setIsFinancialParticipation(bool $isFinancialParticipation): static
    {
        $this->isFinancialParticipation = $isFinancialParticipation;

        return $this;
    }

    public function getFinancialParticipationAmount(): ?string
    {
        return $this->financialParticipationAmount;
    }

    public function setFinancialParticipationAmount(?string $financialParticipationAmount): static
    {
        $this->financialParticipationAmount = $financialParticipationAmount;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): static
    {
        $this->Category = $Category;

        return $this;
    }

    public function getOrganisator(): ?User
    {
        return $this->organisator;
    }

    public function setOrganisator(?User $organisator): static
    {
        $this->organisator = $organisator;

        return $this;
    }

    /**
     * @return Collection<int, Registration>
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): static
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations->add($registration);
            $registration->setEvent($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): static
    {
        if ($this->registrations->removeElement($registration)) {
            // set the owning side to null (unless already changed)
            if ($registration->getEvent() === $this) {
                $registration->setEvent(null);
            }
        }

        return $this;
    }

    public function getPlace(): ?string
    {
        return $this->place;
    }

    public function setPlace(string $place): static
    {
        $this->place = $place;

        return $this;
    }

    public function getTotalAmountCollected(): ?string
    {
        return $this->totalAmountCollected;
    }

    public function setTotalAmountCollected(?string $totalAmountCollected): static
    {
        $this->totalAmountCollected = $totalAmountCollected;

        return $this;
    }

    /**
     * @return Collection<int, Payment>
     */
    public function getPayments(): Collection
    {
        return $this->payments;
    }

    public function addPayment(Payment $payment): static
    {
        if (!$this->payments->contains($payment)) {
            $this->payments->add($payment);
            $payment->setEvent($this);
        }

        return $this;
    }

    public function removePayment(Payment $payment): static
    {
        if ($this->payments->removeElement($payment)) {
            // set the owning side to null (unless already changed)
            if ($payment->getEvent() === $this) {
                $payment->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setEvent($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            if ($comment->getEvent() === $this) {
                $comment->setEvent(null);
            }
        }

        return $this;
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Event;
use App\Entity\Registration;
use App\Entity\Notification;
use App\Entity\Comment;
use App\Entity\User;
use App\Form\InviteType;
use App\Form\CommentType;
use App\Repository\EventRepository;
use App\Repository\UserRepository;
use App\Form\EventType;
use App\Repository\CommentRepository;
use App\Repository\RegistrationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\SecurityBundle\Security;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use App\Service\DateFormatterService;

class EventController extends AbstractController
{
    private $entityManager;
    private $userRepository;
    private $commentRepository;

    public function __construct(EntityManagerInterface $entityManager, UserRepository $userRepository, CommentRepository $commentRepository)
    {
        $this->entityManager = $entityManager;
        $this->userRepository = $userRepository;
        $this->commentRepository = $commentRepository;
    }

    private function getLoggedUser(): ?User
    {
        return $this->getUser();
    }

    private function denyUnlessLogged()
    {
        if (!$this->getLoggedUser()) {
            throw new AccessDeniedException();
        }
    }

    #[Route('/evenement', name: 'app_event')]
    public function index(EventRepository $eventRepository, Security $security, DateFormatterService $dateFormatter): Response
    {
        setlocale(LC_TIME, 'fr_FR.UTF-8');

        $user = $security->getUser();

        if ($user) {
            $events = $eventRepository->findEventsWithoutUnconfirmedRegistration($user);
        } else {
            $events = $eventRepository->findLimitedEvents();
        }

        return $this->render('event/index.html.twig', [
            'events' => $events,
            'user' => $user,
            'dateFormatter' => $dateFormatter,
        ]);
    }

    #[Route('/evenement/{id}', name: 'app_event_show')]
    public function show(Event $event, RegistrationRepository $registrationRepository, Security $security, Request $request): Response
    {
        $user = $security->getUser();
        $existingRegistration = $registrationRepository->findOneBy(['event' => $event, 'user' => $user]);
        $confirmedParticipants = $registrationRepository->findBy(['event' => $event, 'hasConfirmed' => true]);

        $comment = new Comment();
        $commentForm = $this->createForm(CommentType::class, $comment);
        $commentForm->handleRequest($request);

        if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            $comment->setEvent($event);
            $comment->setUser($user);
            $comment->setCreatedAt(new \DateTimeImmutable());

            $this->entityManager->persist($comment);
            $this->entityManager->flush();

            return $this->redirectToRoute('app_event_show', ['id' => $event->getId()]);
        }

        $hasParticipated = $existingRegistration ? $existingRegistration->isHasParticipated() : false;

        return $this->render('event/show.html.twig', [
            'event' => $event,
            'existingRegistration' => $existingRegistration,
            'participants' => $confirmedParticipants,
            'comment_form' => $commentForm->createView(),
            'hasParticipated' => $hasParticipated, // Added parameter
        ]);
    }

    #[Route('/evenement/{id}/invite', name: 'app_event_invite')]
    public function invite(Request $request, Event $event, RegistrationRepository $registrationRepository, EntityManagerInterface $entityManager): Response
    {
        $this->denyUnlessLogged();

        if ($this->getLoggedUser() !== $event->getOrganisator()) {
            throw new AccessDeniedException('Vous n\'êtes pas autorisé à inviter des utilisateurs à cet événement.');
        }

        $form = $this->createForm(InviteType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $selectedUsers = $form->get('users')->getData();

            foreach ($selectedUsers as $user) {
                $existingRegistration = $registrationRepository->findOneBy([
                    'user' => $user,
                    'event' => $event,
                ]);

                if ($existingRegistration) {
                    continue;
                }

                $registration = new Registration();
                $registration->setEvent($event);
                $registration->setUser($user);
                $registration->setRegistrationDate(new \DateTime('now'));
                $registration->setIsInvited(true);
                $registration->setHasConfirmed(false);
                $registration->setHasParticipated(false);

                $entityManager->persist($registration);

                $notification = new Notification();
                $notification->setUser($user);

                $eventLink = $this->generateUrl('app_event_show', ['id' => $event->getId()], UrlGeneratorInterface::ABSOLUTE_URL);
                $notificationMessage = sprintf(
                    'Vous avez été invité à l\'événement <a href="%s">%s</a>.',
                    $eventLink,
                    htmlspecialchars($event->getTitle(), ENT_QUOTES, 'UTF-8')
                );

                $notification->setMessage($notificationMessage);

                $entityManager->persist($notification);
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_event_show', ['id' => $event->getId()]);
        }

        return $this->render('event/invite.html.twig', [
            'event' => $event,
            'inviteForm' => $form->createView(),
        ]);
    }

    #[Route('/evenement/{id}/participate', name: 'app_event_participate')]
    public function participate(Event $event, RegistrationRepository $registrationRepository, EntityManagerInterface $em, Security $security): Response
    {
        $this->denyUnlessLogged();
        $user = $this->getLoggedUser();

        if (null === $user) {
            return $this->redirectToRoute('app_login');
        }

        $existingRegistration = $registrationRepository->findOneBy(['event' => $event, 'user' => $user]);

        if ($existingRegistration) {
            if (!$existingRegistration->isHasConfirmed()) {
                $existingRegistration->setHasConfirmed(true);
                $em->flush();
            } else {
            }
        } else {
            $registration = new Registration();
            $registration->setEvent($event);
            $registration->setUser($user);
            $registration->setHasConfirmed(true);
            $registration->setRegistrationDate(new \DateTime());

            $em->persist($registration);
            $em->flush();
        }

        return $this->redirectToRoute('app_event_show', ['id' => $event->getId()]);
    }

    #[Route('/evenement/{id}/cancel-participation', name: 'app_event_cancel_participation')]
    public function cancelParticipation(Event $event, RegistrationRepository $registrationRepository, EntityManagerInterface $em, Security $security): Response
    {
        $this->denyUnlessLogged();
        $user = $this->getLoggedUser();

        $existingRegistration = $registrationRepository->findOneBy(['event' => $event, 'user' => $user]);

        if ($existingRegistration && $existingRegistration->isHasConfirmed()) {
            $existingRegistration->setHasConfirmed(false);
            $em->flush();
        }

        return $this->redirectToRoute('app_event_show', ['id' => $event->getId()]);
    }

    #[Route('/mon-compte/evenements', name: 'app_account_myevents')]
    public function indexAccountEvent(Security $security, UserRepository $userRepository, EventRepository $eventRepository): Response
    {
        $this->denyUnlessLogged();
        $user = $this->getLoggedUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        $events = $eventRepository->findEventsByUser($user);

        return $this->render('account_event/index.html.twig', [
            'user' => $user,
            'events' => $events,
        ]);
    }

    #[Route('/mon-compte/evenements/new', name: 'app_account_event_new')]
    public function new(Request $request, EntityManagerInterface $entityManager, Security $security): Response
    {
        $event = new Event();

        $this->denyUnlessLogged();
        $user = $this->getLoggedUser();

        $event->setOrganisator($user);

        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $startDateString = $form->get('startDate')->getData();
            $startDate = \DateTime::createFromFormat('Y-m-d H:i', $startDateString);
            $event->setStartDate($startDate);

            $endDateString = $form->get('endDate')->getData();
            $endDate = \DateTime::createFromFormat('Y-m-d H:i', $endDateString);
            $event->setEndDate($endDate);

            if ($event->isIsFinancialParticipation()) {
                $event->setTotalAmountCollected(0.00);
            }

            $entityManager->persist($event);

            $registration = new Registration();
            $registration->setEvent($event);
            $registration->setUser($user);
            $registration->setHasConfirmed(true);
            $registration->setRegistrationDate(new \DateTime());
            $entityManager->persist($registration);

            $entityManager->flush();

            return $this->redirectToRoute('app_event_show', ['id' => $event->getId()]);
        }

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Découvrez et Participez à des Événements avec FriendEventManager{% endblock %}
{% block meta_title %}Participez à des Événements Uniques - FriendEventManager{% endblock %}
{% block meta_description %}Explorez une large gamme d'événements publics sur FriendEventManager. Trouvez et rejoignez des événements passionnants adaptés à tous les goûts et intérêts.{% endblock %}

{% block body %}
<div class="custom-container">
    <header>
        <h1 id="discover-events">Participer à de Nouveaux Événements</h1>
    </header>
<main aria-label="Les événements à venir">
<section class="events">
    <div class="event-cards">
        {% for event in events %}
            {% if not event.isPrivate %}
                <article class="event-card">
                    <a href="{{ path('app_event_show', {'id': event.id}) }}" aria-label="Voir l'événement: {{ event.title }}">
                        <h3 class="event-title">{{ event.title }}</h3>
                        <div class="event-organisator"> Organisé par <strong>{{event.organisator.firstName}} {{event.organisator.lastName}}</strong></div>
                        {% if event.category.imageUrl %}
                            <img src="{{ event.category.imageUrl }}" alt="Image de l'événement: {{ event.title }}" loading="lazy">
                        {% endif %}
                        <div class="event-description">
                            <p><strong>{{event.category.name}}</strong></p>
                            <p class="event-place"><i class="fas fa-map-marker-alt"></i> {{event.place}}</p>
                            <time datetime="{{ event.startDate|date('Y-m-d') }}"> 
                                <i class="fas fa-calendar-alt"></i> 
                                Du {{ event.startDate ? event.startDate|date('d/m/Y à H\\hi') : '' }} 
                            </time>
                            <time datetime="{{ event.endDate|date('Y-m-d') }}"> 
                                au {{ event.endDate|date('d/m/Y à H\\hi') }}
                            </time>
                        </div>
                    </a>
                </article>
            {% endif %}
        {% endfor %}
    </div>
</section>
</main>
</div>
{% endblock %}

templates/event/invite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inviter un utilisateur{% endblock %}

{% block body %}
<div class="custom-container">

    <div class="invite-form">
        {{ form_start(inviteForm) }}
            {{ form_widget(inviteForm) }}
        {{ form_end(inviteForm) }}
    </div>
</div>

{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ event.title }}{% endblock %}
{% block meta_title %}{{ event.title|e }}{% endblock %}
{% block meta_description %}Participez à l'événement {{ event.title|e }} - {{ event.category.name|e }} - organisé par {{ event.organisator.firstName|e }} {{ event.organisator.lastName|e }}{% endblock %}
{% block canonical %}
    <link rel="canonical" href="{{ url('app_event_show', {'id': event.id}) }}" />
{% endblock %}


{% block body %}
<div class="custom-container single-event">
    <header class="event-title">
        <h1>{{ event.title }}</h1>
        <p><i>Organisé par <strong>{{ event.organisator.firstName }} {{ event.organisator.lastName }}</strong></i></p>
    </header>

    <main aria-label="Détails de l'événement">
        {% if app.user == event.organisator %}
            <section class="event-management">
                {% include 'event/includes/_event-management.html.twig' %}
            </section>
        {% endif %}

        <section class="single-event-img">
            {% include 'event/includes/_event-image.html.twig' %}
        </section>

        <section class="event-participation">
            {% include 'event/includes/_event-participation.html.twig' %}
        </section>

        <section class="event-description">
            {% include 'event/includes/_event-description.html.twig' %}
        </section>

        {% if existingRegistration is not null and existingRegistration.isHasConfirmed %}
            <section class="event-financial-contribution">
                {% include 'event/includes/_event-financial-contribution.html.twig' %}
            </section>
        {% endif %}

        <section class="event-participant-list">
            {% include 'event/includes/_event-participant-list.html.twig' %}
        </section>

        {% if existingRegistration is not null and existingRegistration.isHasConfirmed %}
            <section class="event-comment">
                {% include 'event/includes/_event-comment.html.twig' %}
            </section>
        {% endif %}
    </main>
</div>
{% endblock %}